<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: Xmlrpclib | Dark Matter in Cyberspace]]></title>
  <link href="http://leetschau.github.io/blog/categories/xmlrpclib/atom.xml" rel="self"/>
  <link href="http://leetschau.github.io/"/>
  <updated>2016-04-09T20:50:36+08:00</updated>
  <id>http://leetschau.github.io/</id>
  <author>
    <name><![CDATA[Li Chao]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[Publish Blogs on Cnblogs.com]]></title>
    <link href="http://leetschau.github.io/blog/2014/03/18/085501/"/>
    <updated>2014-03-18T08:55:01+08:00</updated>
    <id>http://leetschau.github.io/blog/2014/03/18/085501</id>
    <content type="html"><![CDATA[<p>Some frequently used action about post on cnblogs:</p>

<pre><code>import xmlrpclib

serviceUrl, appKey = 'http://www.cnblogs.com/yourusername/services/metaweblog.aspx', 'yourusername'
username, password = 'yourusername', 'yourpassword'
server = xmlrpclib.ServerProxy(serviceUrl)

res = server.metaWeblog.getRecentPosts('', username, password, 10)
print('no of posts: %d' % len(res))
print('list posts: %s' %res)

cat = server.metaWeblog.getCategories('', username, password)
print('no of categories: %d' %len(cat))
print('list categories: %s' %cat)

post = {'title':'My 4th Post', 'description':'some test text here\na new line', 'mt_keywords': 'test, demo'}
postid = server.metaWeblog.newPost('', username, password, post, True)
print('postid is: %s' % postid)

post = server.metaWeblog.getPost('3604635', username, password)
print('Get Post: %s' % post)
</code></pre>

<p>When publish new post, we often meet this error:</p>

<pre><code>Traceback (most recent call last):
  File "config.py", line 18, in &lt;module&gt;
    postid = server.metaWeblog.newPost('', usr, passwd, post, True)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: &lt;Fault 500: u'\u62b1\u6b49\uff01\u5df2\u8d85\u8fc7\u5f53\u65e5\u535a\u6587\u53d1\u5e03\u6570\u91cf100\u7bc7\u9650\u5236\uff01\u4eca\u5929\u65e0\u6cd5\u7ee7\u7eed\u53d1\u5e03\uff01'&gt;
</code></pre>

<p>To see the error information, open a python shell, run following code</p>

<pre><code>print(u'\u62b1\u6b49\uff01\u5df2\u8d85\u8fc7\u5f53\u65e5\u535a\u6587\u53d1\u5e03\u6570\u91cf100\u7bc7\u9650\u5236\uff01\u4eca\u5929\u65e0\u6cd5\u7ee7\u7eed\u53d1\u5e03\uff01')
</code></pre>

<p>Output:</p>

<pre><code>抱歉！已超过当日博文发布数量100篇限制！今天无法继续发布！
</code></pre>
]]></content>
  </entry>
  
</feed>
